(function(){function r(){q=window.jQuery.noConflict(!0);t()}function t(){"undefined"===typeof window.$&&"undefined"!==typeof q&&(window.$=q);(function(d,g){var f=function(d,c){function b(){this.prefix="__vnative";this.random=(1E32*c.Math.random()).toString(36)}b.prototype={set:function(a,h,c,b){a=this.prefix+a;var e=new Date;e.setTime(e.getTime()+864E5*c);c="expires="+e.toUTCString();a=a+"="+h+"; "+c+"; ";b&&(a+=" path="+b+";");d.cookie=a},get:function(a){a=this.prefix+a;a+="=";for(var h=d.cookie.split(";"),
c=0;c<h.length;c++){for(var b=h[c];" "==b.charAt(0);)b=b.substring(1);if(0==b.indexOf(a))return b.substring(a.length,b.length)}return""},erase:function(a){a=this.prefix+a;d.cookie=a+'=; expires=Thu, 01 Jan 1970 00:00:00 UTC";'}};return new b}(d.document,d),l=function(d,c){function b(){this.regions=[]}b.prototype={treeDepth:function(a){a=a.children();for(var h=0;0<a.length;)a=a.children(),h+=1;return h},_nodeIdentifier:function(a){var h="",h=h+a.prop("tagName");a.attr("id")&&(h+="#"+a.attr("id").replace(/[0-9]+/g,
""));a.attr("class")&&(a=a.attr("class").split(/\s+/),3>=a.length&&(a.sort(),c.each(a,function(a,b){b=b.replace(/[0-9]+/g,"");h+="."+b})));return h},_combComparison:function(a){for(var b={},d={},n=0,e=a.length;n<e;++n){var k=c(a[n]),g=k.prop("tagName");if("SCRIPT"!=g&&"NAV"!=g&&"A"!=g){var f=this._nodeIdentifier(k);"undefined"===typeof b[f]&&(b[f]=0);b[f]++;d[f]=n}}n=!1;for(f in b)2<b[f]&&(n=!0,e=c(a[d[f]]),this.regions.push(e));return n},mdr:function(a){if(3<=this.treeDepth(a)){a=a.children();this._combComparison(a);
for(var b=0,d=a.length;b<d;++b){var e=c(a[b]),f=e.prop("tagName");"SCRIPT"!=f&&"NAV"!=f&&"A"!=f&&this.mdr(e)}}}};return new b}(d,g),e=function(d,c){function b(){this.loaded=!1;this.result=this.parser=null;this.domain="track.vnative.com"}b.prototype={init:function(){this.loaded=!0;this.parser=new d.UAParser},_result:function(){var a=this.parser.getResult();this.result={screen:{height:d.screen.height,width:d.screen.width},device:{browser:a.browser.name,os:a.os.name,model:a.device.model||"Desktop"}}},
send:function(a){this._result();this.result.aduid=a.aduid;this.result.cid=a.cid;this.result.loc=btoa(d.location.hostname);c.ajax({url:"//"+this.domain+"/impression/?callback=?",type:"GET",async:!0,jsonpCallback:"jsonCallback",contentType:"application/json",dataType:"jsonp",data:this.result}).always(function(){})}};var a=new b;c.ajaxSetup({cache:!0});c.getScript("//serve.vnative.com/uaparser.min.js",function(b){a.init()});return a}(d,g),m=function(){function k(){this.domain="clicks99.com";this.trackingDomain=
"track.vnative.com";this.contentOpts={adunit:null,publisher:null,campaign:null,dest:null,time:d.Date.now()};this.dm=l;this.ckid=null}k.prototype={_init:function(c){var b=this.contentOpts;b.adunit=g(".byvnative").data("slot")||"slot";b.publisher=g(".byvnative").data("client")||"publisher";b.publisher=b.publisher.replace(/pub-/g,"");b.dest=c._url;b.campaign=c._id;f.get("Tracking")||f.set("Tracking",f.random,365);this.ckid=f.get("Tracking");e.send({aduid:b.adunit,cid:b.campaign})},get:function(c){var b=
this;g.ajax({url:"//"+b.domain+"/campaign/serve?xapi=c99ads&callback=?",type:"GET",async:!0,jsonpCallback:"jsonCallback",contentType:"application/json",dataType:"jsonp"}).done(function(a){b._init(a);c.call(b,null,a)}).fail(function(a){c.call(b,a,null)})},_trackLink:function(){var c=this.contentOpts,b;b="//"+(this.trackingDomain+"/click");b+="?slot="+c.adunit;b+="&pid="+c.publisher;b+="&cid="+c.campaign;b+="&ckid="+this.ckid;b+="&dest="+btoa(c.dest);return b+="&ti="+c.time},_attach:function(c){c=g(c);
var b=this._trackLink();c.on("click",function(a){a.preventDefault();d.location.href=b})},replace:function(c,b){var a=this;a._attach(c);if(3==c.nodeType){var d=g(c).text(),d=d.replace(/\s/g,"");0!=d.length&&isNaN()&&(c.nodeValue=11>=d.length?"":b)}else 1==c.nodeType&&g(c).contents().each(function(){a.replace(this,b)})}};return new k}();d[d.vNativeObject||"vnative"]=m})(window,q);$(document).ready(function(){for(var d=$("body").children(),g=window[window.vNativeObject||"vnative"],f=g.dm,l={},e=0,m=
d.length;e<m;++e){var k=$(d[e]),c=k.prop("tagName");if("DIV"==c||"SECTION"==c||"ARTICLE"==c)c=f.treeDepth(k),Array.isArray(l[c])||(l[c]=[]),l[c].push(k)}d=Object.keys(l);d=d.map(function(a){return Number(a)});d.sort(function(a,b){return a-b});l=function(a,b){var c,d=[];for(c=b.pop();a[c]&&0<a[c].length;)d.push(a[c].pop());for(c=b.pop();a[c]&&0<a[c].length;)d.push(a[c].pop());return d}(l,d);e=0;for(m=l.length;e<m;++e)f.mdr(l[e]);var b={};$.each(f.regions,function(a,c){var d=c.parent().children().length,
e=c.prop("tagName");"SCRIPT"!=e&&"NAV"!=e&&"A"!=e&&(b[d]=c)});d=Object.keys(b);d=d.map(function(a){return Number(a)});d.sort(function(a,b){return a-b});e=0;for(f=-1;e<d.length;)m=b[d[e]].find("a").text().length,m>f&&(f=m,k=b[d[e]]),e++;g.get(function(a,b){var c;if(!a){var d=k.clone().insertAfter(k);c=d.find("a");"undefined"!==typeof c&&c.attr("href",b._url);(c=d.find("img"))&&c.attr("src",b._image);this.replace(d[0],b._title)}})})}var q;if(void 0===window.jQuery){var p=document.createElement("script");
p.setAttribute("type","text/javascript");p.setAttribute("src","//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js");p.readyState?p.onreadystatechange=function(){"complete"!=this.readyState&&"loaded"!=this.readyState||r()}:p.onload=r;(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(p)}else q=window.jQuery,t()})();